"""
Skykin — Intent Classification Model Trainer
File:    model.py
Run:     python model.py
Reads:   data/synthetic_sessions.csv   (generated by scripts/generate_data.py)
Saves:   models/intent_model.pkl
"""

import os
import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

# ─────────────────────────────────────────────────────────────
#  CONFIGURATION
# ─────────────────────────────────────────────────────────────

RANDOM_STATE         = 42
TEST_SIZE            = 0.20    # 80% train / 20% test
CONFIDENCE_THRESHOLD = 0.70    # minimum score to trigger a reward (SRS §9)

DATA_PATH  = os.path.join("data",   "synthetic_sessions.csv")
MODEL_DIR  = "models"
MODEL_PATH = os.path.join(MODEL_DIR, "intent_model.pkl")


# ─────────────────────────────────────────────────────────────
#  STEP 1 — LOAD DATA
# ─────────────────────────────────────────────────────────────

print("=" * 55)
print("  Skykin — Intent Model Trainer")
print("=" * 55)

print(f"\n[1/4] Loading data from {DATA_PATH} ...")

if not os.path.exists(DATA_PATH):
    raise FileNotFoundError(
        f"\nData file not found at '{DATA_PATH}'.\n"
        "Run  python scripts/generate_data.py  first."
    )

df = pd.read_csv(DATA_PATH)

print(f"      Loaded {len(df):,} sessions.")
print(f"\n      Label distribution:")
print(df["label"].value_counts().to_string())


# ─────────────────────────────────────────────────────────────
#  STEP 2 — SPLIT
#  stratify=y keeps class proportions equal in both splits
#  so no intent is over- or under-represented in the test set.
# ─────────────────────────────────────────────────────────────

print(f"\n[2/4] Splitting: {int((1-TEST_SIZE)*100)}% train / {int(TEST_SIZE*100)}% test ...")

X = df["features"]
y = df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=TEST_SIZE,
    random_state=RANDOM_STATE,
    stratify=y,
)

print(f"      Train: {len(X_train):,}  |  Test: {len(X_test):,}")


# ─────────────────────────────────────────────────────────────
#  STEP 3 — BUILD & TRAIN PIPELINE
#
#  TfidfVectorizer
#    ngram_range=(1,2)  → catches phrases like "coffee near" or
#                         "add to cart", not just single words
#    min_df=2           → ignore tokens seen in fewer than 2 sessions
#    max_features=5000  → cap vocabulary size for speed
#    sublinear_tf=True  → log-scale term frequencies to reduce
#                         the dominance of very common words
#
#  RandomForestClassifier
#    n_estimators=200   → more trees = more stable predictions
#    max_depth=20       → limits overfitting on clean synthetic data
#    class_weight=balanced → handles any slight class imbalance
#    n_jobs=-1          → use all available CPU cores
# ─────────────────────────────────────────────────────────────

print("\n[3/4] Training TF-IDF + Random Forest pipeline ...")

pipeline = Pipeline([
    ("tfidf", TfidfVectorizer(
        ngram_range=(1, 2),
        min_df=2,
        max_features=5_000,
        sublinear_tf=True,
    )),
    ("clf", RandomForestClassifier(
        n_estimators=200,
        max_depth=20,
        class_weight="balanced",
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )),
])

pipeline.fit(X_train, y_train)
print("      Training complete.")


# ─────────────────────────────────────────────────────────────
#  STEP 4 — EVALUATE
#  predict_proba gives per-class probabilities. We take the
#  highest probability as the confidence score for that
#  prediction — exactly what the SRS requires.
# ─────────────────────────────────────────────────────────────

print("\n[4/4] Evaluating on held-out test set ...")

y_pred       = pipeline.predict(X_test)
y_proba      = pipeline.predict_proba(X_test)
confidences  = y_proba.max(axis=1)

print("\n  Classification Report:")
print(classification_report(y_test, y_pred, target_names=sorted(pipeline.classes_)))

print("  Confusion Matrix (rows = actual, cols = predicted):")
cm    = confusion_matrix(y_test, y_pred, labels=sorted(pipeline.classes_))
cm_df = pd.DataFrame(cm, index=sorted(pipeline.classes_), columns=sorted(pipeline.classes_))
print(cm_df.to_string())

above = (confidences >= CONFIDENCE_THRESHOLD).sum()
pct   = above / len(confidences) * 100
print(f"\n  Confidence >= {CONFIDENCE_THRESHOLD}: "
      f"{above:,} / {len(confidences):,} predictions ({pct:.1f}%)")
print(f"  Mean: {confidences.mean():.3f}  "
      f"Min: {confidences.min():.3f}  "
      f"Max: {confidences.max():.3f}")


# ─────────────────────────────────────────────────────────────
#  SAVE MODEL ARTIFACT
#  Bundle everything into one .pkl so app.py loads a single
#  file and never has hardcoded thresholds or intent lists.
# ─────────────────────────────────────────────────────────────

os.makedirs(MODEL_DIR, exist_ok=True)

artifact = {
    "pipeline":          pipeline,
    "threshold":         CONFIDENCE_THRESHOLD,
    "intents":           list(pipeline.classes_),
    "training_samples":  len(X_train),
    "test_samples":      len(X_test),
    "model_version":     "2.0",
}

joblib.dump(artifact, MODEL_PATH)

print(f"\n  Model saved → {MODEL_PATH}")
print("\n" + "=" * 55)
print("  Done. Start the API with:")
print("  uvicorn app:app --reload")
print("=" * 55)