"""Generate golden feature vectors for the Flutter SDK's Dart port.

The Dart port of the scam detector's feature pipeline must match this one to
1e-6 before it is allowed to score anything. `FRONTEND_MODEL_GUIDE.md` omits
several load-bearing scikit-learn defaults (`norm="l2"` above all), so the
Python is the specification and this script is how that is enforced.

Run from `fraude_ml/`:

    .venv/bin/python tools/gen_scam_goldens.py

Pin scikit-learn to **1.7.2** — the version that fitted
`models/artifacts/tfidf_vectorizer.joblib`. `strip_accents="unicode"` and the
tokenizer are version-sensitive, so generating goldens under a different
version would encode a contract the shipped vocabulary does not honour.

Output is written sparsely: 30 dense 3,016-float rows would be a ~1.5 MB
fixture, and all but a handful of TF-IDF columns are zero.
"""

import json
import os
import sys

import joblib

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from src.features.build_features import FeatureExtractor  # noqa: E402

ARTIFACT_DIR = os.path.join(os.path.dirname(__file__), "..", "models", "artifacts")
TFLITE_DIR = os.path.join(os.path.dirname(__file__), "..", "models", "tflite")
OUT_PATH = os.path.join(
    os.path.dirname(__file__),
    "..", "..", "..", "..",
    "Skykin-flutter-sdk", "skykin_flutter_sdk",
    "test", "fixtures", "scam_golden_vectors.json",
)

# Chosen to exercise every branch the Dart port has to reproduce, not to look
# representative: the IP-host quirk, Amharic script, non-ASCII digits, emoji
# (code points vs UTF-16 units), control characters, accented Latin
# (strip_accents), multiple URLs, no URL at all, and a bare-URL browse.
SAMPLES = [
    ("Urgent Telebirr Alert: verify now http://telebirr-kyc.xyz/login", "message"),
    ("http://192.168.1.105/cbe-sec-login", "url"),
    ("Hello, are we still on for lunch tomorrow?", "message"),
    ("ማስጠንቀቂያ: የ Telebirr መለያዎ ታግዷል። verify now http://telebirr-kyc-verify.xyz/login", "message"),
    ("FREE ENTRY to win 1000 BIRR! Claim at bit.ly/abc123 now", "message"),
    ("alert\nverify your account", "message"),  # control chars deleted, not spaced
    ("Café naïve résumé update", "message"),     # strip_accents="unicode"
    ("Your OTP is ፩፪፫ do not share", "message"),  # Ethiopic digits: str.isdigit()
    ("Win a prize 🎉🎉 click https://a7x-9z-claim.top/go", "message"),  # non-BMP
    ("Visit https://example.com and http://tinyurl.com/xyz today", "message"),
    ("CBE: your account is SUSPENDED, verify at http://cbe-verify.sbs", "message"),
    ("no urls here at all just plain text", "message"),
    ("https://play.google.com/store/apps/details?id=com.example.app", "url"),
    ("bit.ly/2xY", "url"),
    ("http://sub.deep.nested.example.co.uk/path?q=1", "url"),
    ("", "message"),
    ("   ", "message"),
    ("a", "message"),  # single char: token_pattern needs 2+
    ("dashen bank bonus reward claim now", "message"),
    ("BOATING supplies sale", "message"),  # 'boa' substring matches inside 'boating'
]


def main() -> None:
    vectorizer = joblib.load(os.path.join(ARTIFACT_DIR, "tfidf_vectorizer.joblib"))
    with open(os.path.join(TFLITE_DIR, "model_manifest.json")) as fh:
        manifest = json.load(fh)
    tabular_order = manifest["tabular_features"]

    extractor = FeatureExtractor()
    cleaner = extractor.cleaner

    records = []
    for raw, mode in SAMPLES:
        text = raw
        if mode == "url" and text.strip():
            # predict.py:_predict_url prepends a scheme, then runs the identical
            # message pipeline.
            if not text.startswith(("http://", "https://")):
                text = "http://" + text

        cleaned = cleaner.clean_text(text, preserve_urls=True)
        # .transform() applies sublinear_tf, idf AND the l2 norm over the
        # 3000-dim block, before any concatenation.
        tfidf_row = vectorizer.transform([cleaned]).toarray()[0]

        feats = extractor.extract_message_features(text)
        tabular = [float(feats[name]) for name in tabular_order]

        sparse = {
            str(i): float(v) for i, v in enumerate(tfidf_row) if v != 0.0
        }
        records.append({
            "raw": raw,
            "mode": mode,
            "cleaned": cleaned,
            "tfidf_sparse": sparse,
            "tfidf_len": int(len(tfidf_row)),
            "tabular": tabular,
        })

    out = {
        "_comment": (
            "Generated by fraude_ml/tools/gen_scam_goldens.py with "
            f"scikit-learn {__import__('sklearn').__version__}. Do not hand-edit."
        ),
        "sklearn_version": __import__("sklearn").__version__,
        "tabular_order": tabular_order,
        "records": records,
    }

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as fh:
        json.dump(out, fh, indent=1, ensure_ascii=False)
    print(f"wrote {len(records)} golden records -> {os.path.normpath(OUT_PATH)}")


if __name__ == "__main__":
    main()
