"""Generate the shared URL-heuristic parity fixture.

The 9 URL heuristics now exist in three languages: Python (the trainer, and the
specification), Dart (`scam_feature_extractor.dart`), and Kotlin
(`SkykinUrlRiskHeuristics.kt`, which the accessibility service uses because it
cannot run the model). Nothing but a shared fixture keeps them honest — the two
ports must agree with this one exactly, or the browser shield warns on different
things depending on which layer noticed first.

Run from `fraude_ml/`:

    .venv/bin/python tools/gen_url_heuristics_vectors.py

The output is loaded by BOTH the Dart test and the JVM Kotlin test.
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from src.features.build_features import FeatureExtractor  # noqa: E402

SDK_ROOT = os.path.join(
    os.path.dirname(__file__), "..", "..", "..", "..",
    "Skykin-flutter-sdk", "skykin_flutter_sdk",
)
OUT_PATH = os.path.join(SDK_ROOT, "test", "fixtures", "url_heuristics_vectors.json")

# Every branch the ports have to reproduce, including the ones that look wrong
# but are what the model was trained against.
URLS = [
    "http://192.168.1.105/cbe-sec-login",        # IP host: entropy 0, tld "105"
    "https://192.168.1.105:8443/x",              # IP host with a port
    "http://telebirr-kyc.xyz/login",             # high-risk tld + hyphen
    "https://example.com",                        # ordinary
    "https://example.com/path?q=1#frag",         # query + fragment
    "https://play.google.com/store/apps/details?id=com.example.app",
    "https://bit.ly/abc123",                     # shortener
    "https://tinyurl.com/xyz",
    "https://t.co/aaa",
    "https://cutt.ly/bbb",
    "https://sub.deep.nested.example.co.uk/p",   # subdomain depth
    "http://a7x-9z-claim.top/go",                # high entropy + hyphen
    "example.com/no-scheme",                     # scheme prepended
    "localhost:8080/admin",                      # single-label host
    "https://EXAMPLE.COM/UPPER",                 # case
    "https://xn--80ak6aa92e.com/",               # punycode
    "https://example.info/x",                    # high-risk tld, no hyphen
    "https://ጤና.example.org/x",                  # non-ASCII in the URL
    "https://example.cc",
    "",                                           # blank -> all zeros
]

FIELDS = [
    "has_url", "url_count", "url_length", "domain_entropy",
    "is_high_risk_tld", "is_url_shortener", "ip_in_url",
    "subdomain_count", "has_hyphen_in_domain",
]


def main() -> None:
    extractor = FeatureExtractor()
    records = []
    for url in URLS:
        feats = extractor.extract_url_features(url)
        records.append({
            "url": url,
            "features": {k: float(feats[k]) for k in FIELDS},
        })

    out = {
        "_comment": (
            "Generated by fraude_ml/tools/gen_url_heuristics_vectors.py. "
            "Loaded by BOTH the Dart and the Kotlin parity tests. Do not "
            "hand-edit; regenerate after changing build_features.py."
        ),
        "fields": FIELDS,
        "records": records,
    }

    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w") as fh:
        json.dump(out, fh, indent=1, ensure_ascii=False)

    # The Kotlin test needs it on the JVM test classpath too.
    kotlin_path = os.path.join(
        SDK_ROOT, "android", "src", "test", "resources", "url_heuristics_vectors.json"
    )
    os.makedirs(os.path.dirname(kotlin_path), exist_ok=True)
    with open(kotlin_path, "w") as fh:
        json.dump(out, fh, indent=1, ensure_ascii=False)

    print(f"wrote {len(records)} url records to:")
    print(f"  {os.path.normpath(OUT_PATH)}")
    print(f"  {os.path.normpath(kotlin_path)}")


if __name__ == "__main__":
    main()
